# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [43]:
import numpy as np
arr = np.random.uniform(0,20,(4,7))

array([[ 4.01791736,  4.42885849,  5.75216142, 19.43443671,  1.19540394,
        17.7789013 , 12.71200519],
       [17.85358812,  5.9620096 ,  6.10106736, 18.0252873 , 16.57899379,
         0.50054988,  4.93393929],
       [19.16415763,  8.21466511,  1.62262697, 13.44262035, 13.59608477,
        12.29093436,  1.60820508],
       [13.78481175, 16.42458136,  2.08244751,  8.91344675, 15.12691079,
        14.4740384 , 17.621176  ]])

In [44]:
# 2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) 
# чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), 
# в которой сумма значений минимальна.
matrix = np.random.randint(0,10,(8,10))
print(matrix)


array([[0, 2, 7, 3, 5, 6, 7, 1, 9, 9],
       [0, 7, 0, 2, 1, 6, 4, 3, 0, 0],
       [6, 8, 4, 3, 6, 7, 4, 7, 8, 0],
       [4, 1, 6, 2, 9, 1, 6, 1, 4, 9],
       [8, 2, 9, 3, 4, 8, 8, 3, 2, 1],
       [1, 0, 9, 4, 7, 5, 9, 5, 1, 7],
       [2, 2, 5, 0, 8, 6, 5, 9, 6, 6],
       [9, 6, 3, 5, 9, 9, 5, 6, 0, 4]])

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

In [3]:
# 1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, 
# времени его выполнения в минутах и количестве необходимых ингредиентов. 
# Считайте данные из этого файла в виде массива `numpy` типа `int32`, 
# используя `np.loadtxt`. Выведите на экран первые 5 строк массива.
import numpy as np

data_csv = np.loadtxt('minutes_n_ingredients.csv', dtype = 'int32', delimiter = ',', skiprows = 1)

data_csv[:6,:]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14],
       [152828,     40,      7]], dtype=int32)

In [4]:
# 2. Вычислите среднее значение, минимум, максимум 
# и медиану по каждому из столбцов, кроме первого.
min_and_ingredients_column = data_csv[:,1:]

average = np.average(min_and_ingredients_column, axis = 0)
minimum = min_and_ingredients_column.min(axis = 0)
maximum = min_and_ingredients_column.max(axis = 0)
mediana = np.median(min_and_ingredients_column, axis = 0)

print(average)
print(minimum)
print(maximum)
print(mediana)

[2.16010017e+04 9.05528000e+00]
[0 1]
[2147483647         39]
[40.  9.]


In [5]:
# 3. Ограничьте сверху значения продолжительности 
# выполнения рецепта значением квантиля $q_{0.75}$. 
minutes_column = data_csv[:,1:2]
block = np.clip(minutes_column,0,np.quantile(minutes_column, 0.75))
print(block)

check = block.max()
print(check)

[[60.]
 [25.]
 [10.]
 ...
 [65.]
 [ 5.]
 [65.]]
65.0


In [6]:
# 4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. 
# Замените для таких строк значение в данном столбце на 1.
before_min = minutes_column.min(axis = 0)

print(100000 - np.count_nonzero(minutes_column))

for el in np.arange(minutes_column.size):
    if np.count_nonzero(minutes_column[el]) == 0:
        minutes_column[el] = 1
        
after_min = minutes_column.min(axis = 0)

print(before_min, after_min)

479
[0] [1]


In [7]:
# 5. Посчитайте, сколько уникальных рецептов находится в датасете.
np.unique(data_csv, axis = 0).shape[0]

100000

In [8]:
# 6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?
n_ingredients_column = data_csv[:,2:]

different_ingredients = np.unique(n_ingredients_column, axis = 0).shape[0]

print(different_ingredients)

37


In [19]:
# 7. Создайте версию массива, содержащую информацию только о рецептах, 
# состоящих не более чем из 5 ингредиентов.
print(data_csv[data_csv[:, 2] <= 5]) 


[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


In [20]:
# 8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. 
# Найдите максимальное значение этой величины для всего датасета
new_array = np.array([])
min_column = data_csv[:,1:2]
ingredients_column = data_csv[:,2:]

for el in np.arange(min_column.size):
    ing_1_min = ingredients_column[el] / min_column[el]
    new_array = np.append(new_array, ing_1_min)

print(new_array)
print(new_array.max(axis = None))

[0.26666667 0.28       0.6        ... 0.23076923 0.8        0.1       ]
24.0


In [21]:
# 9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью
sorted_array = data_csv[data_csv[:,1].argsort()[::-1]]
average_n_ing = np.average(sorted_array[:101,2:], axis = 0)
print(*average_n_ing)

6.603960396039604


In [22]:
# 10. Выберите случайным образом и выведите информацию о 10 различных рецептах
random_array = np.random.randint(0, 100001, (1, 10))[0]
for el in np.arange(random_array.size):
    print(data_csv[random_array[el]])

[85957    45     7]
[184473     12      7]
[100197     35     10]
[214821     20      7]
[244949     35     22]
[108831    105      9]
[82203    65     3]
[133290     35      8]
[160193     20      5]
[133077     18      6]


In [23]:
# 11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.
average_n_ing = average[1]
count = 0
n_ing = data_csv[:,2:]

for el in np.arange(n_ing.size):
    if n_ing[el] < average_n_ing:
        count+=1
print(((count/n_ing.size)*100)) 

58.802


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [26]:
simple_recipes = ((data_csv[:, 1] <= 20) & (data_csv[:, 2] <= 5)).astype(int)

data_simple_column = np.column_stack((data_csv, simple_recipes))
print(data_simple_column[:5])

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 [ 67660      5      6      0]
 [157911     60     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [27]:
print(np.mean(simple_recipes) * 100)

9.552


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [ ]:
short_recipes = data_csv[data_csv[:, 1] < 10]
standard_recipes = data_csv[(data_csv[:, 1] >= 10) & (data_csv[:, 1] < 20)]
long_recipes = data_csv[data_csv[:, 1] >= 20]

max_len = min(len(short_recipes), len(standard_recipes), len(long_recipes)) #максимальное кол-во рецептов в каждой группе

group_recipes = np.zeros((3, max_len, 3), dtype=int)
group_recipes[0, :len(short_rcps[:max_len])] = short_recipes[:max_len]
group_recipes[1, :len(standard_rcps[:max_len])] = standard_recipes[:max_len]
group_recipes[2, :len(long_rcps[:max_len])] = long_rcp[:max_len]

print(group_recipes)
print(group_recipes.shape)